### PR TITLE
Fix build issue introduced in #25

### LINKED ISSUE #26: Getting a build error with the latest version
Hi,

I have a build script that's pulling in the latest 1.1.2 version as a dependency on graphql 0.9.6, with the following error. It works fine on 1.1.1

├─┬ graphql@0.9.6 
│ └── iterall@1.1.2 

static/js/main.e1f5732b.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/iterall/index.js:644,0]

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Fixes #26

### CODE REVIEW

**Comment by danez** [comment]
Also did run into this. had to downgrade graphql-js

**Comment by zeevgg** [comment]
when would it be published?

**Comment by even42** [comment]
I hope this fix will be merge soon cause I can't deploy my app in production.  Please do it fast :s

**Comment by DxCx** [comment]
#25 also breaks promise rejection,
if the iter.next() rejects, it won't propagate..
can this be fixed as well as part of this PR?

**Comment by IvanGoncharov** [comment]
@DxCx I don't experience the same problem so it's hard for me to fix it.
Can you please open separate issue about it?

@leebyron This issue brakes many builds including apps that use `graphql` package.
Can you please merge this super simple PR?

**Comment by epfisztner** [comment]
@leebyron it would be nice if you merge it and make a new release as soon as possible.

**Comment by leebyron** [comment]
Thanks for fixing this, Ivan!

**Pull request merged**
